version: "3.8"

services:
  frontend:
    build: frontend
    ports:
      - "5173:5173"
    networks:
      - postfeed
    depends_on:
      - backend

  backend:
    build: backend
    ports:
      - "8000:8000"
    networks:
      - postfeed
    depends_on:
      - mongodb
      

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - postfeed
    volumes:
      - mongo_data:/data/db 

networks:
  postfeed:
    driver: bridge

volumes:
  mongo_data:
    driver: local
